pipeline {
    agent any

    environment {
        DOCKERHUB_CREDENTIALS = 'etrichi'
        IMAGE_NAME = 'hounaida202/demo1-app'
        SONAR_TOKEN = credentials('sonar-token')
    }

    stages {
        stage('Checkout') {
            steps {
                git 'https://github.com/Hounaida202/SDMS.git'
            }
        }

        stage('Tests & Quality') {
            steps {
                dir('demo1') {
                    // Tests
                    bat 'mvn clean test'

                    // JaCoCo
                    bat 'mvn jacoco:report jacoco:check'

                    // SonarQube
                    bat 'mvn sonar:sonar -Dsonar.login=%SONAR_TOKEN%'
                }
            }
        }

        stage('Docker') {
            steps {
                dir('demo1') {
                    // Build
                    bat 'docker build -t %IMAGE_NAME% .'

                    // Push
                    withCredentials([usernamePassword(
                        credentialsId: DOCKERHUB_CREDENTIALS,
                        passwordVariable: 'PASS',
                        usernameVariable: 'USER'
                    )]) {
                        bat """
                            echo %PASS% | docker login -u %USER% --password-stdin
                            docker push %IMAGE_NAME%
                        """
                    }
                }
            }
        }

        stage('Deploy') {
            steps {
                dir('demo1') {
                    bat 'docker-compose down || echo ok'
                    bat 'docker-compose up -d'
                    bat 'timeout /t 20 /nobreak'
                    bat 'docker-compose ps'
                }
            }
        }
    }
}