pipeline {
    agent any

    stages {
        stage('Build & Deploy') {
            steps {
                dir('demo1') {
                    bat 'mvn clean package'
                    bat 'docker build -t app .'
                    bat 'docker-compose down || echo ok'
                    bat 'docker-compose up -d'
                }
            }
        }
    }
}