pipeline {
    agent any

    stages {
        stage('Build & Test') {
            steps {
                dir('demo1') {
                    // Test Maven
                    bat 'mvn --version'

                    // Clean et compile
                    bat 'mvn clean compile'

                    // Tests unitaires
                    bat 'mvn test'
                }
            }
        }
    }

    post {
        always {
            echo 'Pipeline completed'
        }
    }
}